image: node:latest

    stages:
      - build

    cache:
      paths:
        - node_modules/

    build:
      stage: build
      script:
        - npm install
        - npm run build
        - tar -zcvf build/FacileThings-linux-x64.tar.gz build/FacileThings-linux-x64
        - tar -zcvf build/FacileThings-win32-x64.tar.gz build/FacileThings-win32-x64
        - tar -zcvf build/FacileThings-darwin-x64.tar.gz build/FacileThings-darwin-x64
      artifacts:
        paths:
          - build/*.tar.gz
